---

- name: Install dnsmasq server
  apt: >
    name=dnsmasq
    state=present
  when: dns

- name: Setup DNS configuration
  copy:
    src: "{{ role_path }}/files/dnsmasq.conf"
    dest: /etc/dnsmasq.conf
    force: yes
  when: dns

- name: Setup DHCP configuration
  copy:
    src: "{{ role_path }}/files/dhclient.conf"
    dest: /etc/dhcp/dhclient.conf
    force: yes
  when: dns

- name: Restart DNS server service
  shell: "/etc/init.d/dnsmasq restart"
  when: dns

- name: ensure quagga is installed
  apt: >
    name=quagga
    state=present

- name: copy over quagga daemons file from template
  template: >
    src=quagga-daemons.conf.j2
    dest=/etc/quagga/daemons
    owner=quagga
    group=quagga
    mode=0600
  notify:
    - restart quagga

# FIXME: will be changed every time, may need to copy empty file
- name: touch required but empty quagga files
  copy: >
    src=empty-file
    dest=/etc/quagga/{{ item }}
    owner=quagga
    group=quagga
    mode=0600
  with_items:
    - bgpd.conf
    - ospf6d.conf
    - ripd.conf
    - ripngd.conf

- name: install zebra and ospfd configuration files
  template: >
    src={{ item }}.j2
    dest=/etc/quagga/{{ item }}
    owner=quagga
    group=quagga
    mode=0600
  with_items:
    - ospfd.conf
    - zebra.conf
  notify:
    - restart quagga

- name: ensure quagga is running
  service: >
    name=quagga
    state=running

- name: get default route
  command: ip -4 route list 0/0
  register: default_route
  changed_when: False

- name: remove default route
  shell: "ip route delete default"
  when: "'10.0.2.2' in default_route.stdout"

- name: set default route to 10.0.10.0/24
  shell: "ip route add 10.0.10.0/24 via 172.0.1.2"
  when: "'10.0.2.2' in default_route.stdout"

- name: set default route to 10.0.20.0/24
  shell: "ip route add 10.0.20.0/24 via 172.0.2.2"
  when: "'10.0.2.2' in default_route.stdout"

- name: set default route
  shell: "ip route add default via {{ router }}"
  when: "'10.0.2.2' in default_route.stdout"

- name: check if 172.0.3.10 has been added
  shell: ip address show | grep 172.0.3.10
  register: vip
  changed_when: False
  retries: 10
  delay: 10
  ignore_errors: True

- name: add 172.0.3.10 as vip
  shell: ip address add 172.0.3.10 dev eth1
  when: vip.rc != 0

- name: Create directories
  shell: "mkdir -p F{{ item[0] }}/{{ item[1]}}/file.txt"
  with_nested:
    - [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20' ]
    - [ 'images', 'tests', 'slides' ]

- name: Run HTTP server
  shell: "sleep 20s; nohup python -m SimpleHTTPServer > webapp.log &"
