---

- name: get default route
  command: ip -4 route list 0/0
  register: default_route
  changed_when: False

- name: set default route
  shell: "ip route delete default && ip route add default via {{ router }}"
  when: "'10.0.2.2' in default_route.stdout"

- name: Add DNS server
  template:
    src: "{{ role_path }}/files/resolv.conf.j2"
    dest: /etc/resolv.conf
    force: yes

- name: Copy traffic generation file
  template:
    src: "{{ role_path }}/files/config.py.j2"
    dest: /home/vagrant/config.py
    force: yes

- name: Copy python scripts
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/vagrant/{{ item }}"
    force: yes
  with_items:
    - gen.py
    - sniffer
