Vagrant.configure("2") do |config|
  config.vm.define "slowloris" do |slowloris|
    slowloris.vm.box = "hashicorp/precise64"
    slowloris.vm.provision :shell, path: "bootstrap.sh"
    slowloris.vm.network :public_network,
      use_dhcp_assigned_default_route: true
  end

  config.vm.define "antiloris" do |antiloris|
    antiloris.vm.box = "hashicorp/precise64"
    antiloris.vm.provision :shell, path: "bootstrap.sh"
    antiloris.vm.provision :shell, path: "install-antiloris.sh"
    antiloris.vm.network :public_network,
      use_dhcp_assigned_default_route: true
  end
end
